Sheep compatiability
systemetric/shepherd-2 pull request #21
Opened 2022-08-17 08:43 UTC by shardros

WIP: This PR will be merged when there is all of the parts which sheep needs to run working.

2022-08-19 17:32 UTC, fenjalien commented
Running this branch on my pi produces this error when the start button is pressed in the editor: 
```
INFO:     127.0.0.1:44546 - "POST /upload/upload HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 151, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/pi/.cache/pypoetry/virtualenvs/shepherd-2-TGIJcPDa-py3.10/lib/python3.10/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/home/pi/.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/shepherd-2/./app/routers.py", line 55, in upload_file
    app.upload.process_uploaded_file(uploaded_file)
  File "/home/pi/shepherd-2/./app/upload.py", line 110, in process_uploaded_file
    shutil.rmtree(config.round_path)
  File "/home/pi/.pyenv/versions/3.10.6/lib/python3.10/shutil.py", line 714, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/pi/.pyenv/versions/3.10.6/lib/python3.10/shutil.py", line 712, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/shepherd-2/usercode/round'
```
The later run request gives a 409
```info
INFO:     127.0.0.1:49338 - "POST /run/start HTTP/1.1" 409 Conflict
```

The output of running pytest is 
```
test/test_editor.py ..                                                             [ 20%]
test/test_home.py .                                                                [ 30%]
test/test_runner.py x..F                                                           [ 70%]
test/test_upload.py FFF                                                            [100%]
```
It looks like the failures are also due to the directory `usercode/round` not exsisting, what is the purpose of this folder @shardros ?

2022-08-19 20:35 UTC, shardros commented
Fixed and tested on fresh install

2022-08-19 20:43 UTC, shardros commented
> It looks like the failures are also due to the directory usercode/round not exsisting, what is the purpose of this folder @shardros ?

This is correct. This is the folder where the usercode which is to be run in the next round is uploaded to. It is now automatically created by shepherd. Logs aren't done in this pr but you can see that the code works by looking `logs.txt`

2022-08-20 13:29 UTC, fenjalien commented
> This is the folder where the usercode which is to be run in the next round is uploaded to.

Ah so `usercode/` is all the code that has been written by the user and `usercode/round/` is the code that will be run when `/run/start` is hit?

2022-08-20 13:30 UTC, shardros commented
> > This is the folder where the usercode which is to be run in the next round is uploaded to.
> 
> Ah so `usercode/` is all the code that has been written by the user and `usercode/round/` is the code that will be run when `/run/start` is hit?

Correct :)

2022-08-20 15:03 UTC, fenjalien requested changes
From running the tests: 
```
test/test_editor.py ..        [ 20%]
test/test_home.py .         [ 30%]
test/test_runner.py xF..   [ 70%]
test/test_upload.py .FF    [100%]
```
`test_start` fails at line [20](https://github.com/systemetric/shepherd-2/blob/18c9b5400693804166bce94a13cfecd273b374ea/test/test_runner.py#L20) due to a timeout. Looks like it comes from [this line](https://github.com/systemetric/shepherd-2/blob/18c9b5400693804166bce94a13cfecd273b374ea/app/routers.py#L33):
```python
type(runner).state.__set__(runner, States.RUNNING)
```
Why is it like this? In fact all of the rest of the tests fail due to this.

2022-08-20 15:35 UTC, fenjalien commented
I've just tried changing this: https://github.com/systemetric/shepherd-2/blob/18c9b5400693804166bce94a13cfecd273b374ea/app/routers.py#L33
to this:
```python
runner.state = States.RUNNING
```
and all tests pass apart from `larg_zip_upload` by timeout. I'm assuming this is due to the shear size its timeout will need to be much longer.

2022-08-20 16:23 UTC, shardros commented on app/editor.py
> +                     f"{filename}")
> From running the tests:
> 
> ```
> test/test_editor.py ..        [ 20%]
> test/test_home.py .         [ 30%]
> test/test_runner.py xF..   [ 70%]
> test/test_upload.py .FF    [100%]
> ```
> 
> `test_start` fails at line [20](https://github.com/systemetric/shepherd-2/blob/18c9b5400693804166bce94a13cfecd273b374ea/test/test_runner.py#L20) due to a timeout. Looks like it comes from [this line](https://github.com/systemetric/shepherd-2/blob/18c9b5400693804166bce94a13cfecd273b374ea/app/routers.py#L33):
> 
> ```python
> type(runner).state.__set__(runner, States.RUNNING)
> ```
> 
> Why is it like this? In fact all of the rest of the tests fail due to this.

This was made in error, I have fixed this and just pushed this.

I've added some doc-strings. I'm not entirely clear on why they need to have the dots removed this is code coppied from `shepherd-1`

2022-08-20 16:25 UTC, shardros commented on app/config.py
> +        # got the better of me
Re-aranged to be in the docstring

2022-08-20 16:25 UTC, shardros commented on app/config.py
> +        #     4) The game image
Resolved into doc string

2022-08-20 16:27 UTC, shardros commented on app/config.py
> +        if config.start_graphic.exists():
Start graphic was set unconditionally on line 48

2022-08-21 20:39 UTC, shardros commented on app/routers.py
> +_logger = logging.getLogger(__name__)
FastAPI has a really not-pythonic logging interfaces I have switched to using `loguru` which does logging much better in my opion and the logs should now appear everywhere.

2022-08-21 20:39 UTC, shardros commented on app/routers.py
> +async def save_file(filename: str, request: Request):
`request.body()` requires to be awaited on which has to happen inside of an `async` function and I didn't convert all of the others to async. We probally should do that at some point but it's not on the critical path to reach our MVP as shepherd-1 does not do this.
https://github.com/systemetric/shepherd-2/issues/15

2022-08-21 20:39 UTC, shardros commented on app/routers.py
> +    contents: str
Not sure what you mean by "singular" would you be able to explain?

2022-08-21 20:39 UTC, shardros commented on install.sh
> +echo "SOLUTION: install.sh is able to compile python3.10 from source do you want to try?"
Agreed, I think it is worth it never the less.

We later check about swap size:
```
# This is a problem on Pi's
echo "Please confirm that you are on a system with >2GB of memory+swap (increase swap if not) [y/n] "
old_stty_cfg=$(stty -g)
stty raw -echo
answer=$( while ! head -c 1 | grep -i '[ny]' ;do true ;done )
stty $old_stty_cfg
if echo "$answer" | grep -iq "^n" ;then
    exit
fi
```

2022-08-21 20:39 UTC, shardros commented on install.sh
> +echo "  - Offical python docs: https://docs.python.org/3/using/unix.html"
Done in commit.

2022-08-21 20:39 UTC, shardros commented on app/routers.py
> +async def save_file(filename: str, request: Request):
Let me know if you disagree with me on this being the right decision

2022-08-28 19:40 UTC, shardros commented
@fenjalien ready for another round of review

2022-08-28 19:41 UTC, merged

2022-08-28 19:42 UTC, shardros commented
You can still retroactively do the code review but we need to move fast